// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/masterslave.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlaveSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SlaveSubscribeRequest) Reset() {
	*x = SlaveSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_masterslave_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveSubscribeRequest) ProtoMessage() {}

func (x *SlaveSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterslave_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveSubscribeRequest.ProtoReflect.Descriptor instead.
func (*SlaveSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_masterslave_proto_rawDescGZIP(), []int{0}
}

type SlaveSubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   *Topic   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SlaveSubscribeResponse) Reset() {
	*x = SlaveSubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_masterslave_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveSubscribeResponse) ProtoMessage() {}

func (x *SlaveSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterslave_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveSubscribeResponse.ProtoReflect.Descriptor instead.
func (*SlaveSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_masterslave_proto_rawDescGZIP(), []int{1}
}

func (x *SlaveSubscribeResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *SlaveSubscribeResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_masterslave_proto protoreflect.FileDescriptor

var file_proto_masterslave_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x6c,
	0x61, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x66, 0x0a,
	0x16, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x28, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x63, 0x0a, 0x0d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x6c, 0x61, 0x76, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_masterslave_proto_rawDescOnce sync.Once
	file_proto_masterslave_proto_rawDescData = file_proto_masterslave_proto_rawDesc
)

func file_proto_masterslave_proto_rawDescGZIP() []byte {
	file_proto_masterslave_proto_rawDescOnce.Do(func() {
		file_proto_masterslave_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_masterslave_proto_rawDescData)
	})
	return file_proto_masterslave_proto_rawDescData
}

var file_proto_masterslave_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_masterslave_proto_goTypes = []interface{}{
	(*SlaveSubscribeRequest)(nil),  // 0: proto.SlaveSubscribeRequest
	(*SlaveSubscribeResponse)(nil), // 1: proto.SlaveSubscribeResponse
	(*Topic)(nil),                  // 2: proto.Topic
	(*Message)(nil),                // 3: proto.Message
}
var file_proto_masterslave_proto_depIdxs = []int32{
	2, // 0: proto.SlaveSubscribeResponse.topic:type_name -> proto.Topic
	3, // 1: proto.SlaveSubscribeResponse.message:type_name -> proto.Message
	0, // 2: proto.masterService.subscribeMaster:input_type -> proto.SlaveSubscribeRequest
	1, // 3: proto.masterService.subscribeMaster:output_type -> proto.SlaveSubscribeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_masterslave_proto_init() }
func file_proto_masterslave_proto_init() {
	if File_proto_masterslave_proto != nil {
		return
	}
	file_proto_pubsub_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_masterslave_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_masterslave_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveSubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_masterslave_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_masterslave_proto_goTypes,
		DependencyIndexes: file_proto_masterslave_proto_depIdxs,
		MessageInfos:      file_proto_masterslave_proto_msgTypes,
	}.Build()
	File_proto_masterslave_proto = out.File
	file_proto_masterslave_proto_rawDesc = nil
	file_proto_masterslave_proto_goTypes = nil
	file_proto_masterslave_proto_depIdxs = nil
}
